# build docs from main branch and push to gh-pages branch to be deployed to repository GitHub pages
name: Build & Deploy Docs

# trunk-ignore(checkov/CKV2_GHA_1)
permissions: write-all

on:
  push:
    branches:
      - main

  # trunk-ignore(yamllint/empty-values)
  workflow_dispatch:

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements_docs.txt
      - run: mkdocs gh-deploy --force
