# this CI workflow checks the documentation for any broken links or errors within documentation files/configuration
# and reports errors to catch errors and never deploy broken documentation
name: MkDocs CI Check
permissions: read-all

on:
  push:
    branches:
      - main
      - develop
      - "*"
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - develop
      - "*"
concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python SDK
        run: pip install -e .

      - name: Install Doc Dependencies
        run: pip install -r requirements_docs.txt

      - name: Build and Test Documentation
        run: mkdocs build
