# check code types with mypy to be sure the static types are correct and make sense

name: MyPy Check
permissions: read-all

on:
  push:
    branches:
      - main
      - develop
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  mypy-test:
    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run MyPy
        run: mypy src/cript/
