# workflow to check our docstring documentation code examples using pytest doctest module to be sure they are all correct

name: Pytest Doctest

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run pytest with doctest
        run: pytest --doctest-modules src/cript/
